(function(g){var window=this;'use strict';var bh=function(z){z.publish("cardstatechange",z.HW()&&z.Gv()?1:0)},Vk=function(z,t){var Y=g.Rb(t),K=Y?t:arguments;
for(Y=Y?0:1;Y<K.length;Y++){if(z==null)return;z=z[K[Y]]}return z},os2=function(z){var t=g.m9(z);
z=g.e0(z);return new g.cJ(t.x,t.y,z.width,z.height)},L6N=function(z,t,Y){var K=K===void 0?{}:K;
var T;return T=g.wt(z,t,function(){g.b9(T);Y.apply(z,arguments)},K)},Qk=function(z){z=g.t2(z);
delete n9[z];g.EN(n9)&&FG&&FG.stop()},IyN=function(){FG||(FG=new g.R0(function(){PIQ()},20));
var z=FG;z.isActive()||z.start()},PIQ=function(){var z=g.Gz();
g.IQ(n9,function(t){ayA(t,z)});
g.EN(n9)||IyN()},cf=function(z,t,Y,K){g.sn.call(this);
if(!Array.isArray(z)||!Array.isArray(t))throw Error("Start and end parameters must be arrays");if(z.length!=t.length)throw Error("Start and end points must be the same length");this.J=z;this.C=t;this.duration=Y;this.U=K;this.coords=[];this.progress=this.N=0;this.W=null},ayA=function(z,t){t<z.startTime&&(z.endTime=t+z.endTime-z.startTime,z.startTime=t);
z.progress=(t-z.startTime)/(z.endTime-z.startTime);z.progress>1&&(z.progress=1);z.N=1E3/(t-z.W);z.W=t;gsF(z,z.progress);z.progress==1?(z.K=0,Qk(z),z.onFinish(),z.ZH()):z.isPlaying()&&z.mP()},gsF=function(z,t){typeof z.U==="function"&&(t=z.U(t));
z.coords=Array(z.J.length);for(var Y=0;Y<z.J.length;Y++)z.coords[Y]=(z.C[Y]-z.J[Y])*t+z.J[Y]},JYz=function(z,t){g.E6.call(this,z);
this.coords=t.coords;this.x=t.coords[0];this.y=t.coords[1];this.z=t.coords[2];this.duration=t.duration;this.progress=t.progress;this.fps=t.N;this.state=t.K},uh=function(z,t,Y,K,T){cf.call(this,t,Y,K,T);
this.element=z},mc6=function(z,t,Y,K,T){if(t.length!=2||Y.length!=2)throw Error("Start and end points must be 2D");
uh.call(this,z,t,Y,K,T)},NI$=function(z){return Math.pow(z,3)},yYj=function(z){return 3*z*z-2*z*z*z},eO6=function(z){g.I.call(this);
this.J=z||window;this.K=[]},kN=function(z){return z.baseUrl||null},$N=function(z,t){return g.cT(g.FJ(z,t),function(Y){return!!Y})},dc_=function(z,t,Y){function K(TE){var h=TE.hovercardButton;
if(!h)return null;h=h.subscribeButtonRenderer;if(!h)return null;var fF=G(h.unsubscribedButtonText),W=G(h.subscribedButtonText);if(h.subscribed){var HI=G(h.subscriberCountWithUnsubscribeText);var bt=G(h.subscriberCountText)}else HI=G(h.subscriberCountText),bt=G(h.subscriberCountWithSubscribeText);var mI=null;if(TE.signinEndpoint){mI=Vk(TE,"signinEndpoint","webNavigationEndpointData","url");if(!mI){var BA,f_;mI=(f_=g.m((BA=h.signInEndpoint)==null?void 0:BA.commandMetadata,g.rP))==null?void 0:f_.url}if(!mI)return null}return fF&&
(W||mI)?{subscribed:h.subscribed,subscribeText:fF,subscribeCount:HI,unsubscribeText:W,unsubscribeCount:bt,enabled:h.enabled,signinUrl:mI,classic:TE.useClassicSubscribeButton}:null}
function T(TE){if(TE){var h=[],fF=TE.videoId;fF&&h.push("v="+fF);(fF=TE.playlistId)&&h.push("list="+fF);(TE=TE.startTimeSeconds)&&h.push("t="+TE);return"/watch?"+h.join("&")}}
function G(TE){if(!TE)return null;var h=TE.simpleText;return h?h:TE.runs?g.FJ(TE.runs,function(fF){return fF.text}).join(""):null}
t=t.endscreenElementRenderer;if(!t)return null;var v=t.style,f=t.endpoint||{},C=null,X=null,O=!1,D=null,M=null,l=null,Z=null,H=!1,U=null,w=null,V=null,u=null,k=null,J=null;if(v==="VIDEO")g.m(f,g.JA)?C=g.m(f,g.JA).url:(J=g.m(f,g.ES),C=T(J)),X=!1,D=z,t.thumbnailOverlays?(O=t.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,M=G(O.text),O=O.style==="LIVE"):M=G(t.videoDuration);else if(v==="PLAYLIST")g.m(f,g.JA)?C=g.m(f,g.JA).url:(J=g.m(f,g.ES),C=T(J)),X=!1,D=z,l=G(t.playlistLength);else if(v===
"CHANNEL"){if(H=Vk(f,"browseEndpoint","browseId"))Z=H,C="/channel/"+Z;X=!1;D="new";(H=!!t.isSubscribe)?U=K(t):w=G(t.subscribersText)}else v==="WEBSITE"?((V=Vk(f,"urlEndpoint","url"))&&(C=V),X=!0,D="new",V=t.icon.thumbnails[0].url):v==="CREATOR_MERCHANDISE"&&(t.productPrice&&(u=G(t.productPrice)),t.additionalFeesText&&(k=G(t.additionalFeesText)),(X=Vk(f,"urlEndpoint","url"))&&(C=X),X=!0,D="new");z=Vk(t,"title","accessibility","accessibilityData","label");var E=t.endpoint?t.endpoint.clickTrackingParams:
null,d="";if(t.metadata){var Yw=G(t.metadata);Yw&&(d=Yw)}return{id:"element-"+Y,type:v,title:G(t.title),metadata:d,callToAction:G(t.callToAction),Tt:t.image,iconUrl:V,left:Number(t.left),width:Number(t.width),top:Number(t.top),aspectRatio:Number(t.aspectRatio),startMs:Math.floor(Number(t.startMs)),endMs:Math.floor(Number(t.endMs)),videoDuration:M,XM:O,playlistLength:l,channelId:Z,subscribeButton:U,subscribersText:w,isSubscribe:H,targetUrl:C||null,Ci:X,sessionData:E?{itct:E}:null,yW2:D,pF:z?z:null,
isPlaceholder:t.isPlaceholder,impressionUrls:$N(t.impressionUrls||[],kN),Iz:$N(t.hovercardShowUrls||[],kN),clickUrls:$N(f.loggingUrls||[],kN),visualElement:g.Vj(t.trackingParams),productPrice:u,additionalFeesText:k,watchEndpoint:J||null}},xcz=function(z,t){var Y={startMs:Math.floor(Number(z.startMs)),
impressionUrls:$N(z.impressionUrls||[],kN),elements:$N(z.elements||[],function(K,T){return dc_(t,K,T)})};
z.trackingParams&&(Y.visualElement=g.Vj(z.trackingParams));return Y},SwW=function(z){g.Zc.call(this,z);
this.W=this.endscreen=null;this.J={};this.N={};this.U=this.L=null;this.B=[];this.K=null;this.P0=!0;this.C=0;z=z.G();this.V=g.us(z)||g.$q(z);this.events=new g.Lt(this);g.a(this,this.events);this.events.D(this.player,g.An("creatorendscreen"),this.onCueRangeEnter);this.events.D(this.player,g.fx("creatorendscreen"),this.onCueRangeExit);this.events.D(this.player,"resize",this.T1);this.events.D(window,"focus",this.of6);this.load();var t=g.WR("STYLE");(g.Jl("HEAD")[0]||document.body).appendChild(t);this.addOnDisposeCallback(function(){g.Ys(t)});
t.sheet&&(t.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),t.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},EsA=function(z){return z.player.getVideoData().rb?"current":z.V?"new":"current"},ox=function(z){return z.player.G().playerStyle==="creator-endscreen-editor"},W6_=function(z){var t=z.player.getVideoData(),Y=t.videoId;
z.W&&z.W.abort();Y={method:"POST",onFinish:function(T){var G=z.W=null;T.status===200&&(T=T.responseText,T.substring(0,3)===")]}"&&(T=T.substring(3),G=JSON.parse(T),G=xcz(G,EsA(z))));L9(z,G)},
urlParams:{v:Y},withCredentials:!0};z.V&&(Y.urlParams.ptype="embedded");var K=t.hP;K&&(Y.postParams={ad_tracking:K});if(t=g.l1w(t))if(t=g.ex(t),t=g.mX(t))z.W=g.nr(t,Y)},L9=function(z,t,Y){Y=Y===void 0?!0:Y;
z.player.xf("creatorendscreen");z.L&&(z.L.dispose(),z.L=null,z.U.dispose(),z.U=null);for(var K=g.r(Object.values(z.J)),T=K.next();!T.done;T=K.next())T.value.dispose();z.J={};z.N={};z.B.length>0&&(z.B.forEach(function(f){f.dispose()}),z.B.length=0);
z.K&&(g.X0(z.K,"ytp-ce-element-show"),z.K.setAttribute("aria-hidden","true"));z.C=0;if((z.endscreen=t)&&t.elements){Y&&ROj(z);Y=[];K=new g.GT(t.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});Y.push(K);z.player.G().J||(z.L=new g.e({Z:"div",j:"ytp-ce-shadow"}),g.c$(z.player,z.L.element,4),z.U=new g.v_(z.L,200));for(K=0;K<t.elements.length;++K){T=t.elements[K];var G=hO_(z,T);if(G){z.J[T.id]=G;z.N[T.id]=T;g.c$(z.player,G.element,4);var v=new g.GT(T.startMs,T.endMs,{id:"ytp-ce-element-"+
T.id,namespace:"creatorendscreen"});Y.push(v);zgK(z,G,T)}else g.aO(new g.E$("buildEndscreenElement null",T))}z.player.Gc(Y);z.T1()}},ROj=function(z){var t=g.FY(),Y=g.Qj();
Y&&t&&z.endscreen.visualElement&&g.tV(g.RO)(void 0,Y,t,z.endscreen.visualElement)},hO_=function(z,t){var Y=null;
switch(t.type){case "VIDEO":z={Z:"div",It:["ytp-ce-element","ytp-ce-video"],Y:{tabindex:"0","aria-label":t.pF||"","aria-hidden":"true"},T:[{Z:"div",j:"ytp-ce-element-shadow"},{Z:"div",j:"ytp-ce-covering-image",Y:Pf(t)},{Z:"div",j:"ytp-ce-covering-shadow-top"},{Z:"a",j:"ytp-ce-covering-overlay",Y:{href:Ix(z,t.targetUrl),tabindex:"-1"},T:[{Z:"div",It:["ytp-ce-video-title","ytp-webkit-ellipsis"],Y:{dir:g.qX(t.title||"")},Lo:t.title},{Z:"div",j:t.XM?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
Lo:t.videoDuration||void 0}]}]};Y=new g.e(z);break;case "PLAYLIST":z={Z:"div",It:["ytp-ce-element","ytp-ce-playlist"],Y:{tabindex:"0","aria-label":t.pF||"","aria-hidden":"true"},T:[{Z:"div",j:"ytp-ce-element-shadow"},{Z:"div",j:"ytp-ce-covering-image",Y:Pf(t)},{Z:"div",j:"ytp-ce-covering-shadow-top"},{Z:"a",j:"ytp-ce-covering-overlay",Y:{href:Ix(z,t.targetUrl),tabindex:"-1"},T:[{Z:"div",It:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],Y:{dir:g.qX(t.title||"")},Lo:t.title},{Z:"div",j:"ytp-ce-playlist-count",
T:[{Z:"div",j:"ytp-ce-playlist-icon"},{Z:"div",j:"ytp-ce-playlist-count-text",Lo:t.playlistLength||void 0}]}]}]};Y=new g.e(z);break;case "CHANNEL":Y={Z:"div",It:["ytp-ce-element","ytp-ce-channel",t.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],Y:{tabindex:"0","aria-label":t.pF||"","aria-hidden":"true"},T:[{Z:"div",j:"ytp-ce-element-shadow"},{Z:"div",j:"ytp-ce-expanding-overlay",T:[{Z:"div",j:"ytp-ce-expanding-overlay-hider"},{Z:"div",j:"ytp-ce-expanding-overlay-background"},{Z:"div",j:"ytp-ce-expanding-overlay-content",
T:[{Z:"div",j:"ytp-ce-expanding-overlay-body",T:[{Z:"div",j:"ytp-ce-expanding-overlay-body-padding",T:[{Z:"a",It:["ytp-ce-channel-title","ytp-ce-link"],Y:{href:Ix(z,t.targetUrl),target:"_blank",tabindex:"-1",dir:g.qX(t.title||"")},Lo:t.title},t.subscribeButton?{Z:"div",j:"ytp-ce-subscribe-container",T:[{Z:"div",j:"ytp-ce-channel-subscribe"}]}:"",t.subscribersText?{Z:"div",j:"ytp-ce-channel-subscribers-text",Lo:t.subscribersText}:"",t.metadata?{Z:"div",It:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],Lo:t.metadata}:""]}]}]}]},{Z:"div",j:"ytp-ce-expanding-image",Y:Pf(t)}]};Y=new g.e(Y);var K=g.NH(document,"div","ytp-ce-channel-subscribe",Y.element)[0];if(t.subscribeButton&&t.channelId){g.f2(K,"ytp-ce-subscribe-button");if(z.player.G().J){var T=null;var G=t.sessionData.itct}else T="endscreen",G=null;T=new g.WD(t.subscribeButton.subscribeText,t.subscribeButton.subscribeCount,t.subscribeButton.unsubscribeText,t.subscribeButton.unsubscribeCount,!!t.subscribeButton.enabled,!!t.subscribeButton.classic,
t.channelId,!!t.subscribeButton.subscribed,T,G,z.player,!1);K.appendChild(T.element);z.B.push(T)}break;case "WEBSITE":z={Z:"div",It:["ytp-ce-element","ytp-ce-website"],Y:{tabindex:"0","aria-label":t.pF||"","aria-hidden":"true"},T:[{Z:"div",j:"ytp-ce-element-shadow"},{Z:"div",j:"ytp-ce-expanding-overlay",T:[{Z:"div",j:"ytp-ce-expanding-overlay-hider"},{Z:"div",j:"ytp-ce-expanding-overlay-background"},{Z:"div",j:"ytp-ce-expanding-overlay-content",T:[{Z:"div",j:"ytp-ce-expanding-overlay-body",T:[{Z:"div",
j:"ytp-ce-expanding-overlay-body-padding",T:[{Z:"div",j:"ytp-ce-website-title",Y:{dir:g.qX(t.title||"")},Lo:t.title},{Z:"div",j:"ytp-ce-website-metadata",Lo:t.metadata},{Z:"a",It:["ytp-ce-website-goto","ytp-ce-link"],Y:{href:Ix(z,t.targetUrl),target:"_blank",tabindex:"-1"},Lo:t.callToAction}]}]}]}]},{Z:"div",j:"ytp-ce-expanding-image",Y:Pf(t)},{Z:"div",j:"ytp-ce-expanding-icon",Y:t4N(t.iconUrl)}]};Y=new g.e(z);break;case "CREATOR_MERCHANDISE":Y="",t.productPrice&&(Y={Z:"div",j:"ytp-ce-merchandise-price-container",
T:[{Z:"div",j:"ytp-ce-merchandise-price",Lo:t.productPrice}]},t.additionalFeesText&&Y.T.push({Z:"div",j:"ytp-ce-merchandise-additional-fees",Lo:t.additionalFeesText})),z={Z:"div",It:["ytp-ce-element","ytp-ce-merchandise"],Y:{tabindex:"0","aria-label":t.pF||"","aria-hidden":"true"},T:[{Z:"div",j:"ytp-ce-element-shadow"},{Z:"div",j:"ytp-ce-expanding-overlay",T:[{Z:"div",j:"ytp-ce-expanding-overlay-hider"},{Z:"div",j:"ytp-ce-expanding-overlay-background"},{Z:"div",j:"ytp-ce-expanding-overlay-content",
T:[{Z:"div",j:"ytp-ce-expanding-overlay-body",T:[{Z:"div",j:"ytp-ce-expanding-overlay-body-padding",T:[{Z:"div",j:"ytp-ce-merchandise-title",Y:{dir:g.qX(t.title||"")},Lo:t.title},Y,{Z:"div",j:"ytp-ce-merchandise-metadata",Lo:t.metadata},{Z:"a",It:["ytp-ce-merchandise-goto","ytp-ce-link"],Y:{href:Ix(z,t.targetUrl),target:"_blank",tabindex:"-1"},Lo:t.callToAction}]}]}]}]},{Z:"div",j:"ytp-ce-expanding-image",Y:Pf(t)},{Z:"div",j:"ytp-ce-merchandise-invideo-cta-container",T:[{Z:"div",j:"ytp-ce-merchandise-invideo-cta",
Lo:t.callToAction||void 0}]}]},Y=new g.e(z)}t.isPlaceholder&&g.f2(Y.element,"ytp-ce-placeholder");return Y},Pf=function(z){if(z.Tt)var t=z.Tt.thumbnails;
return t4N(t?t[t.length-1].url:null)},t4N=function(z){return z?{style:"background-image: url("+z+")"}:{}},zgK=function(z,t,Y){function K(C){C&&(t.listen("blur",function(){C.style.display!="none"&&z.P0&&C.focus()}),t.D(C,"focus",G),t.D(C,"blur",v))}
function T(C){z.C+=C;z.C>0?(g.f2(t.element,"ytp-ce-force-expand"),ax(z,Y.id,!0)):(g.X0(t.element,"ytp-ce-force-expand"),g.X0(t.element,"ytp-ce-element-hover"),ax(z,Y.id,!1))}
function G(){T(1)}
function v(){T(-1)}
t.listen("mouseenter",function(){YE$(z,t,Y)});
t.listen("mouseleave",function(){K1w(z,t,Y)});
z.player.G().J||t.listen("click",function(){g.f2(t.element,"ytp-ce-element-hover")});
t.listen("click",function(C){TSN(z,Y,C)});
t.listen("keypress",function(C){TSN(z,Y,C)});
t.listen("focus",function(){YE$(z,t,Y)});
t.listen("blur",function(){K1w(z,t,Y)});
t.listen("touchstart",function(){YE$(z,t,Y)});
var f=g.yY("ytp-ce-expanding-overlay-hider",t.element);f&&t.D(f,"touchstart",function(C){C.stopPropagation();g.X0(t.element,"ytp-ce-element-hover");g.X0(t.element,"ytp-ce-force-expand")});
t.listen("keydown",function(C){z.P0=C.keyCode===9&&!C.shiftKey});
K(g.yY("ytp-sb-subscribe",t.element));K(g.yY("ytp-sb-unsubscribe",t.element));t.listen("focus",G);t.listen("blur",v)},TSN=function(z,t,Y){if(t.targetUrl&&(!Y||Y.type!=="keypress"||Y.keyCode===13)){for(var K=Y.target;K&&!g.Av(K,"ytp-ce-element");){g.Av(K,"subscribe-label")&&G5W(z,t);
if(g.Av(K,"ytp-ce-channel-subscribe"))return;K=K.parentElement||null}if(!K||g.Av(K,"ytp-ce-element-hover")){Y.preventDefault();Y.stopPropagation();if(K=z.J[t.id])K1w(z,K,t),K.element.blur();if(Y.ctrlKey||Y.metaKey||t.yW2==="new")G5W(z,t),z.player.sendVideoStatsEngageEvent(17,void 0),z.player.pauseVideo(),Y=g.ex(Ix(z,t.targetUrl)),Y=g.mX(Y),g.xP(Y,void 0,t.sessionData);else{var T=g.Sn(z.player.G())||z.player.getVideoData().rb,G=function(){var v=Ix(z,t.targetUrl),f=t.sessionData,C=t.watchEndpoint,X=
g.AV(v);T&&X&&(X.v||X.list)?z.player.WO(X.v,f,X.list,!1,void 0,C||void 0):g.d7(v,f)};
G5W(z,t,function(){z.player.sendVideoStatsEngageEvent(17,G)})}}}},Ix=function(z,t){z=z.player.G();
if(t){if(t.startsWith("//"))return z.protocol+":"+t;if(t.startsWith("/"))return g.YM(z)+t}else return"";return t},YE$=function(z,t,Y){g.Av(t.element,"ytp-ce-element-hover")||(Y.type==="VIDEO"||Y.type==="PLAYLIST"?g.f2(t.element,"ytp-ce-element-hover"):z.player.G().J?(new g.R0(function(){g.f2(t.element,"ytp-ce-element-hover")},200)).start():g.f2(t.element,"ytp-ce-element-hover"),g5(z,Y.Iz),ax(z,Y.id,!0))},K1w=function(z,t,Y){g.X0(t.element,"ytp-ce-element-hover");
g.X0(t.element,"ytp-ce-force-expand");ax(z,Y.id,!1)},ax=function(z,t,Y){z.L&&(Y?z.U.show():z.U.hide());
for(var K=g.r(Object.keys(z.J)),T=K.next();!T.done;T=K.next())T=T.value,T!==t&&g.On(z.J[T].element,"ytp-ce-element-shadow-show",Y)},g5=function(z,t,Y){function K(){G||(T++,T===t.length&&(v.stop(),Y&&Y()))}
if(!t||t.length===0||ox(z))Y&&Y();else{t=vhz(z,t);var T=0,G=!1,v=new g.R0(function(){G=!0;Y&&Y()},1E3,z);
v.start();for(z=0;z<t.length;z++)g.yi(t[z],K)}},G5W=function(z,t,Y){g5(z,t.clickUrls,Y);
(z=g.Qj())&&t.Ci&&g.XL(z,t.visualElement)},vhz=function(z,t){var Y=z.player.getVideoData().clientPlaybackNonce;
z=z.player.getCurrentTime().toFixed(2);Y={CPN:Y,AD_CPN:Y,MT:z};z=[];for(var K=0;K<t.length;K++)z.push(ABz(t[K],Y));return z},ABz=function(z,t){return z.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(Y){var K=unescape(Y);
K=K.substring(1,K.length-1);return t[K]?escape(t[K]):Y})},fkN=function(z){return typeof z==="string"?z:""},JF=function(z,t,Y){for(var K in t)if(t[K]===z)return z;
return Y},C36=function(z,t,Y,K){this.value=z;
this.target=t;this.showLinkIcon=Y;this.K=K},mm=function(z){return z.value?z.value:null},NL=function(z){if(!z)return null;
var t=g.ex(fkN(z.value));t=g.mX(t);if(!t)return null;var Y=JF(z.target,XM2,"current");if(Y==null)z=null;else{var K=z.show_link_icon;z=new C36(t,Y,K==="true"||K==="false"?K==="true":!0,z.pause_on_navigation!=null?z.pause_on_navigation:!0)}return z},ivj=function(z,t,Y){this.type=z;
this.trigger=t;this.url=Y},DAj=function(z){if(!z)return null;
var t=JF(z.type,Ov$),Y=JF(z.trigger,s3_);z=z.url;z=Array.isArray(z)&&z.length?z[0]:z;z=NL(z?z:null);return t?new ivj(t,Y,z):null},M4F=function(z,t,Y,K,T){this.id=z;
this.type=t;this.style=Y;this.data=T;this.action=K||[]},lkK=function(z,t){return g.ON(z.action,t)},ZvW=function(z,t){this.context=z;
this.K=t},qE$=function(z){return z.customMessage?yk("div","iv-card-message",z.customMessage):""},ef=function(z,t){z="background-image: url("+z+");";
var Y=[];t&&Y.push(t);return{Z:"div",j:"iv-card-image",Y:{style:z},T:Y}},pM$=function(z){if(!z.metaInfo||z.metaInfo.length===0)return"";
var t=[];z=g.r(z.metaInfo);for(var Y=z.next();!Y.done;Y=z.next())t.push(yk("li","",Y.value));return{Z:"ul",j:"iv-card-meta-info",T:t}},yk=function(z,t,Y){t?typeof t==="string"?t={"class":t}:Array.isArray(t)&&(t={"class":t.join(" ")}):t={};
t.dir=g.qX(Y);return{Z:z,Y:t,Lo:Y}},rB6=function(z){if(!z.customMessage)return"";
var t=["iv-card-action","iv-card-primary-link"],Y={};z.GQ&&(t.push("iv-card-action-icon"),Y.style="background-image: url("+z.GQ+");");Y.dir=g.qX(z.customMessage);var K=[{Z:"span",Lo:z.customMessage}];z.showLinkIcon&&(K.push("\u00a0"),K.push({Z:"span",j:"iv-card-link-icon"}));return{Z:"div",It:t,Y:Y,T:K}},d5=function(z,t,Y,K){if(K){t=g.r(t);
for(var T=t.next();!T.done;T=t.next())z.K(T.value,K,Y.id,Y.sessionData,Y.HA.click,5)}},Hvj=function(z,t){this.merchant=z;
this.price=t},j36=function(z){var t;
(t=z)&&!(t=z.length>1?z.charAt(0)==="/"&&z.charAt(1)!=="/":z==="/")&&(t=z.replace(/^(https?:)?\/\//,"").split("/",1),t=!t||t.length<1||!t[0]?[]:t[0].toLowerCase().split(".").reverse(),t=t[0]==="com"&&t[1]==="youtube"||t[0]==="be"&&t[1]==="youtu");return t?z.indexOf("/redirect?")===-1:!1},UAW=function(z,t){return t?t:j36(z)?"current":"new"},xN=function(z,t){g.I.call(this);
var Y=this;this.element=z;this.context=t;this.KA=!1;this.B0=new Map;this.dW=new Map;this.context.S.addEventListener(g.An("annotations_module"),function(K){(K=Y.B0.get(K))&&K.apply(Y)});
this.context.S.addEventListener(g.fx("annotations_module"),function(K){(K=Y.dW.get(K))&&K.apply(Y)})},Sf=function(z,t,Y,K,T,G,v){z.context.K.listen(t,"click",function(f){z.O2(Y,K,T,G||[],v||0,f)});
z.context.K.listen(t,"touchstart",function(){z.KA=!1});
z.context.K.listen(t,"touchmove",function(){z.KA=!0})},BSj=function(z){var t;
return((t=g.m(z,g.JA))==null?0:t.url)?g.m(z,g.JA).url:(z=g.m(z,g.ES))&&z.videoId?(t="/watch?v="+z.videoId,z.playlistId&&(t+="&list="+z.playlistId),z.index&&(t+="&index="+z.index),z.startTimeSeconds&&(t+="&t="+z.startTimeSeconds),t):null},ER=function(z,t,Y){return{NP:(z.impressionLoggingUrlsV2s||[]).map(function(K){return K.baseUrl||""}),
click:(Y.loggingUrls||[]).map(function(K){return K.baseUrl||""}),
close:(t.dismissLoggingUrlsV2s||[]).map(function(K){return K.baseUrl||""}),
NV:(t.impressionLoggingUrlsV2s||[]).map(function(K){return K.baseUrl||""}),
Vv:(t.clickLoggingUrlsV2s||[]).map(function(K){return K.baseUrl||""})}},wMF=function(z,t,Y){xN.call(this,t,Y);
var K=this;this.S=z;this.eventId=null;this.eg=this.SL=this.IQ=this.L=this.isInitialized=!1;this.cards=[];this.iW=this.B=this.Nw=this.U=this.XC=this.K=null;this.P0=[];this.J3=this.C=this.Vn=this.qw=null;this.N=0;this.E4=new g.R0(function(){},Y.s4.e_?4E3:3E3);
g.a(this,this.E4);this.T5=new g.R0(function(){});
g.a(this,this.T5);this.eL=new ZvW(Y,function(T,G,v,f,C,X){Sf(K,T,G,v,f,C,X)});
this.V=new g.e({Z:"div",j:"iv-drawer",Y:{id:"iv-drawer"},T:[{Z:"div",j:"iv-drawer-header",Y:{"aria-role":"heading"},T:[{Z:"span",j:"iv-drawer-header-text"},{Z:"button",It:["iv-drawer-close-button","ytp-button"],Y:{"aria-label":"Ocultar tarjetas",tabindex:"0"}}]},{Z:"div",j:"iv-drawer-content"}]});g.a(this,this.V);this.W=this.V.element;this.FC=new g.v_(this.V,330);g.a(this,this.FC);this.LA=g.yY("iv-drawer-header-text",this.W);this.J=g.yY("iv-drawer-content",this.W);this.addCueRange(0,Y.videoData.lengthSeconds*
1E3,"",function(){K.IQ&&Wf(K,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(K.IQ=K.L)&&Rx(K)});
this.U4=new g.Lt(this);g.a(this,this.U4);this.S.addEventListener("videodatachange",this.jG.bind(this))},bv$=function(z,t){t=t.data;
t.autoOpenMs&&z.addCueRange(t.autoOpenMs,0x8000000000000,"",function(){Wf(z,"YOUTUBE_DRAWER_AUTO_OPEN")});
t.autoCloseMs&&z.addCueRange(t.autoCloseMs,0x8000000000000,"",function(){Rx(z)});
var Y=t.headerText;g.Tq(z.LA,Y);z.B&&z.B.setAttribute("title",Y);t.eventId&&(z.eventId=t.eventId);z.qw=g.Vj(t.trackingParams);z.C=g.Vj(t.closeTrackingParams);z.Vn=g.Vj(t.iconTrackingParams)},V4V=function(z,t){var Y=t.cardId?t.cardId:"cr:"+z.N,K=z.S.G().experiments.A3("enable_error_corrections_infocard_web_client");
if(!t.content&&t.teaser.simpleCardTeaserRenderer&&K){var T=t.teaser.simpleCardTeaserRenderer,G=t.icon?t.icon.infoCardIconRenderer:null;t={id:Y,timestamp:z.N,type:"simple",teaserText:g.Hi(T.message),teaserDurationMs:Number(t.cueRanges[0].teaserDurationMs),startMs:Number(t.cueRanges[0].startCardActiveMs),autoOpen:!!t.autoOpen,sessionData:{},sponsored:!1,HA:{},Vs:null,KW:T.trackingParams?g.Vj(T.trackingParams):null,Vn:G&&G.trackingParams?g.Vj(G.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
GQ:null,title:"",customMessage:"",url:null,onClickCommand:T.onTapCommand||null};hF(z,t)}else{var v;if((v=t.content)==null?0:v.simpleCardContentRenderer){if(!t.cueRanges.length)return;G=(T=t.content)==null?void 0:T.simpleCardContentRenderer;T=t.teaser.simpleCardTeaserRenderer;var f=t.icon?t.icon.infoCardIconRenderer:null;t={id:Y,timestamp:z.N,type:"simple",teaserText:g.Hi(T.message),teaserDurationMs:Number(t.cueRanges[0].teaserDurationMs),startMs:Number(t.cueRanges[0].startCardActiveMs),autoOpen:!!t.autoOpen,
sessionData:zO(z,Y,t,G),sponsored:!1,HA:ER(G,T,G.command),Vs:G.trackingParams?g.Vj(G.trackingParams):null,KW:T.trackingParams?g.Vj(T.trackingParams):null,Vn:f&&f.trackingParams?g.Vj(f.trackingParams):null,imageUrl:tw(G.image.thumbnails,290).url,displayDomain:G.displayDomain?g.Hi(G.displayDomain):null,showLinkIcon:!!G.showLinkIcon,GQ:null,title:G.title?g.Hi(G.title):"",customMessage:G.callToAction?g.Hi(G.callToAction):"",url:g.m(G.command,g.JA).url?NL({pause_on_navigation:!z.context.videoData.isLivePlayback,
target:"new",value:g.m(G.command,g.JA).url}):null,onClickCommand:null};hF(z,t)}else{var C;if((C=t.content)==null?0:C.collaboratorInfoCardContentRenderer){if(!t.cueRanges.length)return;T=(G=t.content)==null?void 0:G.collaboratorInfoCardContentRenderer;G=t.teaser.simpleCardTeaserRenderer;f=t.icon?t.icon.infoCardIconRenderer:null;t={id:Y,timestamp:z.N,type:"collaborator",teaserText:g.Hi(G.message),teaserDurationMs:Number(t.cueRanges[0].teaserDurationMs),startMs:Number(t.cueRanges[0].startCardActiveMs),
autoOpen:!!t.autoOpen,sessionData:zO(z,Y,t,T),sponsored:!1,HA:ER(T,G,T.endpoint),Vs:T.trackingParams?g.Vj(T.trackingParams):null,KW:G.trackingParams?g.Vj(G.trackingParams):null,Vn:f&&f.trackingParams?g.Vj(f.trackingParams):null,channelId:g.m(T.endpoint,g.Hy).browseId,customMessage:T.customText?g.Hi(T.customText):null,profileImageUrl:tw(T.channelAvatar.thumbnails,290).url,title:T.channelName?g.Hi(T.channelName):"",metaInfo:[T.subscriberCountText?g.Hi(T.subscriberCountText):""],url:NL({pause_on_navigation:!z.context.videoData.isLivePlayback,
target:"new",value:g.m(T.endpoint,g.Hy).canonicalBaseUrl?g.m(T.endpoint,g.Hy).canonicalBaseUrl:"/channel/"+g.m(T.endpoint,g.Hy).browseId}),onClickCommand:null};hF(z,t)}else{var X;if((X=t.content)==null?0:X.playlistInfoCardContentRenderer){if(!t.cueRanges.length)return;T=(f=t.content)==null?void 0:f.playlistInfoCardContentRenderer;G=t.teaser.simpleCardTeaserRenderer;f=t.icon?t.icon.infoCardIconRenderer:null;t={id:Y,timestamp:z.N,type:"playlist",teaserText:g.Hi(G.message),teaserDurationMs:Number(t.cueRanges[0].teaserDurationMs),
startMs:Number(t.cueRanges[0].startCardActiveMs),autoOpen:!!t.autoOpen,sessionData:zO(z,Y,t,T),sponsored:!1,HA:ER(T,G,T.action),Vs:T.trackingParams?g.Vj(T.trackingParams):null,KW:G.trackingParams?g.Vj(G.trackingParams):null,Vn:f&&f.trackingParams?g.Vj(f.trackingParams):null,Yo:tw(T.playlistThumbnail.thumbnails,258).url,customMessage:T.customMessage?g.Hi(T.customMessage):null,playlistVideoCount:g.Hi(T.playlistVideoCount),title:T.playlistTitle?g.Hi(T.playlistTitle):"",metaInfo:[T.channelName?g.Hi(T.channelName):
"",T.videoCountText?g.Hi(T.videoCountText):""],url:NL({pause_on_navigation:!z.context.videoData.isLivePlayback,target:"new",value:BSj(T.action)}),onClickCommand:null};hF(z,t)}else{var O;if((O=t.content)==null?0:O.videoInfoCardContentRenderer){if(!t.cueRanges.length)return;var D;T=(D=t.content)==null?void 0:D.videoInfoCardContentRenderer;G=t.teaser.simpleCardTeaserRenderer;f=t.icon?t.icon.infoCardIconRenderer:null;t={id:Y,timestamp:z.N,type:"video",teaserText:g.Hi(G.message),teaserDurationMs:Number(t.cueRanges[0].teaserDurationMs),
startMs:Number(t.cueRanges[0].startCardActiveMs),autoOpen:!!t.autoOpen,sessionData:zO(z,Y,t,T),sponsored:!1,HA:ER(T,G,T.action),Vs:T.trackingParams?g.Vj(T.trackingParams):null,KW:G.trackingParams?g.Vj(G.trackingParams):null,Vn:f&&f.trackingParams?g.Vj(f.trackingParams):null,Yo:tw(T.videoThumbnail.thumbnails,258).url,videoDuration:T.lengthString?g.Hi(T.lengthString):null,customMessage:T.customMessage?g.Hi(T.customMessage):null,title:T.videoTitle?g.Hi(T.videoTitle):"",metaInfo:[T.channelName?g.Hi(T.channelName):
"",T.viewCountText?g.Hi(T.viewCountText):""],isLiveNow:!!T.badge,url:NL({pause_on_navigation:!z.context.videoData.isLivePlayback,target:"new",value:BSj(T.action)}),onClickCommand:null};hF(z,t)}}}}}z.N++},tw=function(z,t){for(var Y=-1,K=-1,T=0;T<z.length;T++){if(z[T].height===t||z[T].width===290)return z[T];
((z[T].height||0)<t||(z[T].width||0)<290)&&(Y<0||(z[Y].height||0)<(z[T].height||0)||(z[Y].width||0)<(z[T].width||0))?Y=T:((z[T].height||0)>=t||(z[T].width||0)>=290)&&(K<0||(z[K].height||0)>(z[T].height||0)||(z[K].width||0)>(z[T].width||0))&&(K=T)}return z[K>=0?K:Y]},zO=function(z,t,Y,K){return{feature:Y.feature?Y.feature:"cards",
src_vid:z.context.videoData.videoId,annotation_id:t,ei:z.context.videoData.eventId||"",itct:K.trackingParams||""}},F1N=function(z,t){if(t=nhw(z,t))t===z.K&&(z.K=null),z.S.removeCueRange(t.AL.id),g.Ys(t.FT),g.Zj(z.cards,t),z.Zu(),YH(z)},Wf=function(z,t,Y){if(!z.L){z.FC.show();
z.XC=new g.R0(function(){g.f2(z.context.S.getRootNode(),g.Se.IV_DRAWER_OPEN)},0);
z.XC.start();z.U4.D(z.J,"mousewheel",function(v){z.E4.start();v.preventDefault();v=v||window.event;var f=0;v.type=="MozMousePixelScroll"?f=0==(v.axis==v.HORIZONTAL_AXIS)?v.detail:0:window.opera?f=v.detail:f=v.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?v.wheelDeltaY/-30:v.wheelDeltaY/-1.2:v.wheelDelta/-1.6:v.wheelDeltaY/-3;if(v=f)z.J.scrollTop+=v});
z.L=!0;var K=g.Qj();K&&z.qw&&z.C&&g.f1(K,[z.qw,z.C]);t={TRIGGER_TYPE:t};for(var T=g.r(z.cards),G=T.next();!G.done;G=T.next())G=G.value,G.E0||(G.E0=!0,Q3j(z.context.logger,G.AL.HA.NP,t)),K&&g.f1(K,[G.AL.Vs]);bh(z.S);Y&&(z.U=new g.R0(function(){z.Nw=z.B;z.iW.focus()},330),z.U.start())}},Rx=function(z){z.L&&(z.FC.hide(),g.u9(z.U4),g.X0(z.context.S.getRootNode(),g.Se.IV_DRAWER_OPEN),z.L=!1,bh(z.S),z.U&&z.U.stop(),z.U=new g.R0(function(){z.Nw&&(z.Nw.focus(),z.Nw=null)},330),z.U.start())},cBV=function(z){g.C2(z.EK(),
[g.Se.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.c$(z.S,z.W,5);z.M1();z.B=g.yY("ytp-cards-button",z.S.getRootNode());z.iW=g.yY("iv-drawer-close-button",z.W);z.isInitialized=!0},uZz=function(z){z.P0.push(g.CV("iv-teaser-shown",z.WS,z));
z.P0.push(g.CV("iv-teaser-hidden",z.L62,z));z.P0.push(g.CV("iv-teaser-clicked",z.Ls,z));z.eg=!0},k5A=function(z,t){var Y;
return t.onClickCommand&&((Y=g.m(t.onClickCommand,g.Xj$))==null?void 0:Y.targetId)==="engagement-panel-error-corrections"?(z.J3=t,!0):!1},$A_=function(z,t){z.J3=t;
var Y=z.S.getVideoData();if(!Y)return!1;Y=g.wr(Y);if(Y==null?0:Y.markersMap)for(var K,T=0;((K=Y)==null?void 0:K.markersMap.length)>T;T++){var G=void 0,v=(G=Y)==null?void 0:G.markersMap[T];if(v.key==="ERROR_CORRECTION_MARKERS"&&(G=void 0,(v=(G=v.value)==null?void 0:G.markers)&&v.length>0))return K=void 0,t.startMs=((K=g.m(v[0],g.Kmo))==null?void 0:K.timeRangeStartMillis)||0,z.J3=null,!0}return!1},hF=function(z,t){if(!k5A(z,t)||$A_(z,t)){var Y=ohz(z,t);
if(Y){var K={AL:t,FT:Y.element,E0:!1};if(t.onClickCommand)z.S.X("web_infocards_teaser_show_logging_fix")&&(z.eg||uZz(z),F1N(z,t.id),Y=z.findLastIndex(K),g.w6(z.cards,Y,0,K));else{z.isInitialized||cBV(z);F1N(z,t.id);var T=z.findLastIndex(K);g.w6(z.cards,T,0,K);Y.QK(z.J,T);z.Zu()}t.autoOpen?z.addCueRange(t.startMs,0x8000000000000,t.id,function(){z.L||(z.K=K,YH(z),L1z(z,K),Wf(z,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(Y=z.context.S.getCurrentTime()*1E3,Y<5E3&&Y>t.startMs&&P3j(z,K),z.addCueRange(t.startMs,
t.startMs+1,t.id,function(){P3j(z,K)}),YH(z))}}},ohz=function(z,t){switch(t.type){case "simple":z=z.eL;
var Y=t.displayDomain?{Z:"div",j:"iv-card-image-text",Lo:t.displayDomain}:void 0;var K=rB6(t);Y={Z:"div",It:["iv-card"],T:[{Z:"a",j:"iv-click-target",Y:{href:t.url?mm(t.url)||"":""},T:[ef(t.imageUrl,Y),{Z:"div",j:"iv-card-content",T:[yk("h2",void 0,t.title),K]}]}]};Y=new g.e(Y);d5(z,g.mc("iv-click-target",Y.element),t,t.url);t=Y;break;case "collaborator":z=z.eL;Y={Z:"div",It:["iv-card","iv-card-channel"],T:[{Z:"a",It:["iv-click-target"],Y:{href:mm(t.url)||"","data-ytid":t.channelId},T:[ef(t.profileImageUrl),
{Z:"div",j:"iv-card-content",T:[qE$(t),{Z:"h2",j:"iv-card-primary-link",Lo:t.title},pM$(t)]}]}]};Y=new g.e(Y);d5(z,g.mc("iv-click-target",Y.element),t,t.url);t=Y;break;case "playlist":z=z.eL;Y={Z:"div",It:["iv-card","iv-card-playlist"],T:[{Z:"a",j:"iv-click-target",Y:{href:mm(t.url)||""},T:[ef(t.Yo,{Z:"div",j:"iv-card-image-overlay",T:[{Z:"span",j:"iv-card-playlist-video-count",Lo:t.playlistVideoCount}]}),{Z:"div",j:"iv-card-content",T:[qE$(t),yk("h2","iv-card-primary-link",t.title),pM$(t)]}]}]};
Y=new g.e(Y);d5(z,g.mc("iv-click-target",Y.element),t,t.url);t=Y;break;case "productListing":z=z.eL;var T=t.offers.length!=0;Y=["iv-card"];K="";var G=rB6(t);T&&(Y.push("iv-card-product-listing"),K="iv-card-primary-link",G=t.offers[0],T=[],G.price&&T.push({Z:"div",j:"iv-card-offer-price",Lo:G.price}),G.merchant&&T.push({Z:"div",j:"iv-card-offer-merchant",Lo:G.merchant}),G={Z:"div",T:T});T=t.url?mm(t.url)||"":"";Y={Z:"div",It:Y,Y:{tabindex:"0"},T:[{Z:"a",It:["iv-card-image","iv-click-target"],Y:{style:"background-image: url("+
t.imageUrl+");",href:T,"aria-hidden":"true",tabindex:"-1"}},{Z:"div",j:"iv-card-content",T:[t.sponsored?{Z:"div",j:"iv-card-sponsored",T:["Patrocinado",{Z:"div",j:"iv-ad-info-container",T:[{Z:"div",j:"iv-ad-info",Lo:"{{adInfo}}"},{Z:"div",j:"iv-ad-info-icon-container",T:[{Z:"div",j:"iv-ad-info-icon"},{Z:"div",j:"iv-ad-info-callout"}]}]}]}:"",{Z:"a",j:"iv-click-target",Y:{href:T},T:[yk("h2",K,t.title),G]}]}]};Y=new g.e(Y);K=g.WR("span");g.Tq(K,"Ves este producto porque consideramos que es importante para el video. Es posible que Google reciba compensaciones del comerciante.");
Y.TV(K,"adInfo");d5(z,g.mc("iv-click-target",Y.element),t,t.url);t=Y;break;case "video":z=z.eL;K=t.videoDuration?{Z:"span",j:"iv-card-video-duration",Lo:t.videoDuration}:void 0;G=t.isLiveNow?{Z:"span",It:["yt-badge","yt-badge-live"],Lo:"EN DIRECTO AHORA"}:null;T={Z:"div",It:["iv-card","iv-card-video"],T:[{Z:"a",j:"iv-click-target",Y:{href:((Y=t.url)==null?void 0:mm(Y))||""},T:[ef(t.Yo,K),{Z:"div",j:"iv-card-content",T:[qE$(t),yk("h2","iv-card-primary-link",t.title),pM$(t),G]}]}]};Y=new g.e(T);d5(z,
g.mc("iv-click-target",Y.element),t,t.url);t=Y;break;default:return null}return t},IkK=function(z){if(z.K)return z.K.AL.type==="productListing";
if(z.S.X("enable_wn_infocards")){var t;return!((t=z.cards)==null||!t.length)&&g.Qh(z.cards,function(Y){return Y.AL.type==="productListing"})}return g.Qh(z.cards,function(Y){return Y.AL.type==="productListing"})},YH=function(z){g.On(z.S.getRootNode(),"ytp-cards-shopping-active",IkK(z))},P3j=function(z,t){if(!g.Av(z.S.getRootNode(),"ytp-cards-teaser-shown")){if(z.K!==t){var Y=g.Qj(),K=z.K?z.K.AL.Vn:z.Vn;
Y&&K&&g.C1(Y,[K]);z.K=t;YH(z)}(Y=z.isInitialized&&z.EK().style.display=="none")||(Y=z.context.S.getPlayerState(),K=Y===0&&z.context.S.getCurrentTime()===0,Y=!(Y===1||Y===3||K));Y||t.AL.teaserDurationMs&&z.S.Dj(!0,{teaserText:t.AL.teaserText,durationMs:t.AL.teaserDurationMs,onClickCommand:t.AL.onClickCommand});z.T5.isActive()||((!z.L||!z.E4.isActive()&&z.SL)&&L1z(z,t),z.T5.start(910+t.AL.teaserDurationMs))}},L1z=function(z,t){z.V.Mj?(t=new cf([0,
z.J.scrollTop],[0,t.FT.offsetTop],600,yYj),z.context.L.listen(t,"animate",function(Y){z.J.scrollTop=Y.y}),z.context.L.listen(t,"finish",function(Y){z.J.scrollTop=Y.y}),t.play()):(z.V.KU(!0),z.J.scrollTop=t.FT.offsetTop,z.V.KU(!1))},Ky=function(z){return z.K&&z.K.AL?z.K.AL:z.cards[0]&&z.cards[0].AL?z.cards[0].AL:null},nhw=function(z,t){return g.ON(z.cards,function(Y){return Y.AL.id===t})},TO=function(z,t,Y){xN.call(this,z,t);
this.annotation=Y;this.isActive=!1},ak6=function(z){var t=z.annotation.data;
"start_ms"in t&&"end_ms"in t&&z.addCueRange(Number(t.start_ms),Number(t.end_ms),z.annotation.id,function(){z.show()},function(){z.hide()})},GO=function(z,t,Y){TO.call(this,z,t,Y);
this.J=null;this.C=!1;this.L=null;this.W=!1;this.K=this.N=this.U=null},ghA=function(z,t){var Y=Y===void 0?0:Y;
var K=os2(t).width;g.gZ(t,K);Y=new mc6(t,[K,t.offsetTop],[K-K-Y,t.offsetTop],200,NI$);g.a(z,Y);z.context.L.listen(Y,"begin",function(){g.dZ(t,!0)});
Y.play()},NSN=function(z,t){if(t.channel_name){var Y=z.createElement({Z:"div",
It:["iv-branding-context-name"],Lo:t.channel_name}),K=z.createElement({Z:"div",It:["iv-branding-context-subscribe"]}),T=t.standalone_subscribe_button_data;T&&(z.K=new g.WD(T.subscribeText,T.subscribeCount,T.unsubscribeText,T.unsubscribeCount,!!T.enabled,!!T.classic,t.channel_id,!!T.subscribed,T.feature,t.session_data.itct,z.context.S,!1),z.K.QK(K));var G=z.createElement({Z:"div",It:["iv-branding-context-subscribe-caret"]}),v=z.createElement({Z:"div",It:["branding-context-container-inner"]});v.appendChild(G);
v.appendChild(Y);v.appendChild(K);g.dZ(v,!1);var f=z.createElement({Z:"div",It:["branding-context-container-outer"]});f.appendChild(v);g.$R(f,"right",t.image_width+"px");g.hl(z.EK(),f);z.L=new g.R0(function(){JB_(z,v,f)},500);
g.a(z,z.L);z.context.K.listen(z.EK(),"mouseover",function(){mAF(z,v,f,G,t.image_height)});
z.context.K.listen(z.EK(),"mouseout",function(){z.L.start()})}},mAF=function(z,t,Y,K,T){z.L.stop();
if(!z.W){var G=g.e0(t);z.K||(t.style.width=g.aH(G.width,!0),Y.style.width=g.aH(G.width,!0));g.$R(K,"top",G.height-Math.max(Math.min(G.height,T)/2+10,20)+"px");g.$R(K,"right","1px");z.W=!0;g.dZ(t,!0);z.U=new g.R0(function(){g.f2(this.EK(),"iv-branding-active")},0,z);
z.U.start()}},JB_=function(z,t,Y){g.X0(z.EK(),"iv-branding-active");
z.N=new g.R0(function(){g.dZ(t,!1);z.K||(Y.style.width=g.aH(0,!0))},250);
z.N.start();z.W=!1},yB$=function(z,t,Y,K,T,G,v){this.K=z;
this.L=t;this.s4=Y;this.videoData=K;this.logger=T;this.S=G;this.J=v},egj=function(z,t,Y){TO.call(this,z,t,Y);
var K=this;this.B=this.isCollapsed=this.V=!1;this.N=5E3;this.J=this.L=this.K=this.W=null;this.C=this.createElement({Z:"div",It:["iv-promo-contents"]});this.U=new g.R0(function(){K.K.setAttribute("aria-hidden","true");g.dZ(K.L,!1);g.dZ(K.J,!0)},700,this);
g.a(this,this.U)},xA2=function(z){var t=z.annotation.data;
if(z.annotation.style==="cta")var Y=6;else if(z.annotation.style==="video"||z.annotation.style==="playlist")Y=7;z.N=t.collapsedelay_ms||z.N;var K=["iv-promo","iv-promo-inactive"];z.EK().setAttribute("aria-hidden","true");z.EK().setAttribute("aria-label","Promoci\u00f3n");z.EK().tabIndex=0;var T=z.annotation.Of(),G=t.image_url;if(G){var v=z.createElement({Z:"div",It:["iv-promo-img","iv-click-target"]});G=z.createElement({Z:"img",Y:{src:G,"aria-hidden":"true"}});v.appendChild(G);t.video_duration&&!t.is_live?
(G=z.createElement({Z:"span",j:"iv-promo-video-duration",Lo:t.video_duration}),v.appendChild(G)):t.playlist_length&&(G=z.createElement({Z:"span",j:"iv-promo-playlist-length",Lo:t.playlist_length.toString()}),v.appendChild(G));T&&Sf(z,v,T,z.annotation.id,t.session_data,void 0,Y)}T?(G=z.createElement({Z:"a",j:"iv-promo-txt"}),g.Sx(G,mm(T)),z.K=G):z.K=z.createElement({Z:"div",j:"iv-promo-txt"});switch(z.annotation.style){case "cta":case "website":var f=z.createElement({Z:"p",T:[{Z:"strong",Lo:t.text_line_1}]});
var C=z.createElement({Z:"p",T:[{Z:"span",j:"iv-promo-link",Lo:t.text_line_2}]});if(G=t.text_line_3){K.push("iv-promo-website-card-cta-redesign");var X=z.createElement({Z:"button",It:["iv-promo-round-expand-icon","ytp-button"]});G=z.createElement({Z:"button",It:["iv-button","iv-promo-button"],T:[{Z:"span",j:"iv-button-content",Lo:G}]});var O=z.createElement({Z:"div",j:"iv-promo-button-container"});O.appendChild(G);T&&Sf(z,z.EK(),T,z.annotation.id,t.session_data,void 0,Y)}g.f2(z.K,"iv-click-target");
T&&Sf(z,z.K,T,z.annotation.id,t.session_data,void 0,Y);break;case "playlist":case "video":f=z.createElement({Z:"p",T:[{Z:"span",Lo:t.text_line_1}]}),C=z.createElement({Z:"p",T:[{Z:"strong",Lo:t.text_line_2}]}),t.is_live&&(f=C,C=z.createElement({Z:"span",It:["yt-badge","iv-promo-badge-live"],Lo:"EN DIRECTO AHORA"})),g.f2(z.K,"iv-click-target"),T&&Sf(z,z.K,T,z.annotation.id,t.session_data,void 0,Y),K.push("iv-promo-video")}f&&z.K.appendChild(f);C&&z.K.appendChild(C);z.C.appendChild(z.K);O&&z.C.appendChild(O);
Y=z.createElement({Z:"div",j:"iv-promo-actions"});z.J=z.createElement({Z:"button",It:["iv-promo-expand","ytp-button"]});z.J.title="Expandir";z.context.K.listen(z.J,"click",function(D){dAW(z,5E3,D)});
Y.appendChild(z.J);g.dZ(z.J,!1);z.context.K.listen(z.EK(),"mouseover",z.A8,z);z.context.K.listen(z.EK(),"mouseout",z.dZ,z);z.context.K.listen(z.EK(),"touchend",function(D){dAW(z,5E3,D)});
z.L=z.createElement({Z:"button",It:["iv-promo-close","ytp-button"]});z.L.title="Cerrar";z.context.K.listen(z.L,"click",z.annotation.style==="cta"&&t.text_line_3?z.Fe:z.D8,z);Y.appendChild(z.L);g.C2(z.EK(),K);v&&(g.hl(z.EK(),v),X&&v.appendChild(X));g.hl(z.EK(),z.C);g.hl(z.EK(),Y)},dAW=function(z,t,Y){Y.stopPropagation();
SEN(z);EhN(z,t);z.K.focus()},W12=function(z){z.isCollapsed||z.B||z.W||(g.f2(z.EK(),"iv-promo-collapsed"),z.isCollapsed=!0,z.U.start())},SEN=function(z){z.U.stop();
z.isCollapsed&&(g.iz(z.EK(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),z.isCollapsed=!1,z.K&&z.K.removeAttribute("aria-hidden"),g.dZ(z.J,!1),g.dZ(z.L,!0))},EhN=function(z,t){z.W||(z.W=g.Ia(function(){Rgw(this);
W12(this)},t,z))},Rgw=function(z){z.W&&(g.eP.clearTimeout(z.W),z.W=null)},hgF=function(z){this.S=z},Q3j=function(z,t,Y){t&&(Y?vm(z,t.map(function(K){return g.ub(K,Y)})):vm(z,t))},vm=function(z,t,Y,K){var T=1,G=void 0,v=-1;
if(Y){var f=!1;G=function(){T--;T||f||(clearTimeout(v),f=!0,Y())};
v=setTimeout(function(){f=!0;Y()},1E3)}t=g.r(t||[]);
for(var C=t.next();!C.done;C=t.next())C=C.value,T++,g.yi(C,G);K&&(T++,K!==0&&z.S.sendVideoStatsEngageEvent(K,G))},zGA=function(z){g.Zc.call(this,z);
var t=this;this.P0=this.B=!1;this.loadNumber=0;this.N={};this.logger=new hgF(this.player);this.W=new g.Lt(this);this.U=this.C=null;this.events=new g.Lt(this);this.l1=this.V=this.K=null;this.J3=[];g.a(this,this.W);this.W.D(this.player,"onVideoAreaChange",function(){t.publish("onVideoAreaChange")});
this.W.D(this.player,"onHideControls",function(){t.publish("onHideControls")});
this.W.D(this.player,"onShowControls",function(){t.publish("onShowControls")});
this.W.D(this.player,"resize",function(K){t.publish("resize",K)});
this.W.D(this.player,"presentingplayerstatechange",function(K){t.publish("presentingplayerstatechange",K)});
this.subscribe("presentingplayerstatechange",this.Ra,this);this.subscribe("resize",this.ge,this);this.player.G().SL.subscribe("vast_info_card_add",this.x7,this);g.a(this,this.events);this.eL=this.createElement({Z:"div",j:"video-custom-annotations"});this.J=new g.e({Z:"div",It:["ytp-player-content","ytp-iv-player-content"]});g.a(this,this.J);g.c$(this.player,this.J.element,4);this.J.hide();this.L=new g.e({Z:"div",It:["ytp-iv-video-content"]});g.a(this,this.L);z=this.createElement({Z:"div",j:"video-annotations"});
z.appendChild(this.eL);this.L.element.appendChild(z);this.Jz()&&this.load();var Y=this.createElement({Z:"style"});(g.Jl("HEAD")[0]||document.body).appendChild(Y);this.addOnDisposeCallback(function(){g.Ys(Y)});
if(z=Y.sheet)z.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),z.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),z.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),z.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),z.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),z.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),z.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),z.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),z.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),z.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},tiF=function(z){z=z.createElement({Z:"div",
It:["annotation","annotation-type-custom"]});g.dZ(z,!1);return z},YIj=function(z,t){t=!t.isCued()&&!g.x(t,1024);
z.J.KU(t);z.L.KU(t)},KK_=function(z,t,Y){z.B=!0;
z.U=g.nr(t,Y)},TNQ=function(z,t){for(var Y={},K=g.r(t.attributes),T=K.next();!T.done;T=K.next())T=T.value,Y[T.name]=T.nodeValue;
for(K=0;K<t.childNodes.length;K++)if(T=t.childNodes[K],g.hh(T)&&T.nodeType==1){if(Y[T.tagName])var G=Y[T.tagName];else if(T.tagName==="data"){T.childNodes.length>0&&(G=T.childNodes[0].nodeValue,Y[T.tagName]=typeof G==="string"?G.trim():G);continue}else G=[],Y[T.tagName]=G;T&&T.tagName==="TEXT"?T.childNodes.length===1&&T.childNodes[0].nodeType===3?G.push(T.childNodes[0].nodeValue):G.push(""):T&&G.push(TNQ(z,T))}return Y},f0N=function(z){var t=z.player.getVideoData();
if(t.U4){var Y=z.player.G().SL.get(t.videoId);if(Y){var K={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(T,G,v){T=z.loadNumber;G=t.videoId;z.loaded&&z.loadNumber===T&&z.player.getVideoData().videoId===G&&(v=g.Z7(v)&&v.responseXML?v.responseXML:null)&&GoN(z,v)}};
g.TZ()&&(K.onFinish=vrF(z,K.onFinish));K.postParams={ic_only:"1"};AK6(K,Y);z.B=!0;g.nr(t.U4,K)}}},AK6=function(z,t){z.method="POST";
z.postParams=z.postParams||{};t.N1&&(z.postParams.ic_coll=t.N1);t.B9&&(z.postParams.ic_xml=t.B9);t.rB&&(z.postParams.ic_track=t.rB)},C_j=function(z){var t=new g.e({Z:"div"});
g.dZ(t.element,!1);var Y=new wMF(z.player,t.element,Aw(z));g.a(Y,t);t.QK(z.J.element);Y.jE();return Y},i4w=function(z,t){var Y,K;
if(t=(Y=t.getWatchNextResponse())==null?void 0:(K=Y.cards)==null?void 0:K.cardCollectionRenderer)z.P0=!0,XhF(z,t),t.headerText&&z.l1&&(Y=g.Hi(t.headerText),z.l1.setAttribute("title",Y))},Aw=function(z){if(!z.V){var t=new eO6(z);
g.a(z,t);var Y=new g.ZR(z);g.a(z,Y);z.V=new yB$(t,Y,z.player.G(),z.player.getVideoData(),z.logger,z.player,z.hU)}return z.V},GoN=function(z,t){var Y=!1,K=t.getElementsByTagName("annotations");
if(K&&!(K.length<1)&&(K=K[0].getAttribute("itct"))){var T=g.Qj();if(T){var G=g.FY();G&&g.tV(g.WZ)(void 0,T,G,[g.Vj(K)])}}t=t.getElementsByTagName("annotation");for(K=0;K<t.length;K++){G=TNQ(z,t[K]);T=null;try{if(G){var v=G.id,f=/.+/;var C=typeof v==="string"&&f!=null&&v!=null&&v.match(f)?v:"";var X=JF(G.type,O4Q),O=JF(G.style,sRw),D=fkN(G.data),M=D.length!==0?JSON.parse(D):{};var l=G.action;G=DAj;if(l==null)var Z=null;else if(g.Rb(l)){f=[];for(var H=g.r(l),U=H.next();!U.done;U=H.next()){var w=G(U.value);
w&&f.push(w)}Z=f}else{var V=G(l);Z=V?[V]:[]}T=C&&X?new M4F(C,X,O,Z,M):null}else T=null}catch(Yw){}if(T)if(T.type==="branding"||T.type==="promotion"){G=z;f=T;var u=tiF(G),k=null;switch(f.type){case "branding":if(G.player.G().YG)break;G.J.element.appendChild(u);k=new GO(u,Aw(G),f);break;case "promotion":g.c$(G.player,u,4),k=new egj(u,Aw(G),f)}k&&k.jE();if(G=k)g.a(z,G),z.N[T.id]=G}else if(T.type==="card"||T.type==="drawer"){z.K||(z.K=C_j(z),g.a(z,z.K));if(T.type==="card"){u=z.K;var J=(Y=T)&&Y.data&&
Y.data.card_type;T=Y.data;if(J)switch(G=T.tracking||{},G={NP:G.impression,click:G.click,close:G.close,NV:G.teaser_impression,Vv:G.teaser_click},f=T.tracking_params||{},k=null,J){case "collaborator":Y={id:Y.id,timestamp:T.timestamp||0,type:T.card_type,teaserText:T.teaser_text,teaserDurationMs:T.teaser_duration_ms,startMs:T.start_ms,autoOpen:T.auto_open||!1,sessionData:T.session_data||{},sponsored:T.sponsored||!1,HA:G,Vs:f.card?g.Vj(f.card):null,KW:f.teaser?g.Vj(f.teaser):null,Vn:f.icon?g.Vj(f.icon):
null,channelId:T.channel_id,customMessage:T.custom_message?T.custom_message:null,profileImageUrl:T.image_url,title:T.title,metaInfo:T.meta_info,url:NL({pause_on_navigation:T.pause_on_navigation,target:T.target||"new",value:T.url}),onClickCommand:null};hF(u,Y);break;case "playlist":Y={id:Y.id,timestamp:T.timestamp||0,type:T.card_type,teaserText:T.teaser_text,teaserDurationMs:T.teaser_duration_ms,startMs:T.start_ms,autoOpen:T.auto_open||!1,sessionData:T.session_data||{},sponsored:T.sponsored||!1,HA:G,
Vs:f.card?g.Vj(f.card):null,KW:f.teaser?g.Vj(f.teaser):null,Vn:f.icon?g.Vj(f.icon):null,Yo:T.image_url,playlistVideoCount:T.playlist_video_count,customMessage:T.custom_message?T.custom_message:null,title:T.title,metaInfo:T.meta_info,url:NL({pause_on_navigation:T.pause_on_navigation,target:T.target||"new",value:T.url}),onClickCommand:null};hF(u,Y);break;case "productListing":T.signin_url&&(k=NL({target:"current",value:T.signin_url}));J=[];for(var E=T.offers||[],d=0;d<E.length;d++)J.push(new Hvj(g.ly(E[d].merchant),
g.ly(E[d].price)));Y={id:Y.id,timestamp:T.timestamp||0,type:T.card_type,teaserText:T.teaser_text,teaserDurationMs:T.teaser_duration_ms,startMs:T.start_ms,autoOpen:T.auto_open||!1,sessionData:T.session_data||{},sponsored:T.sponsored||!1,HA:G,Vs:f.card?g.Vj(f.card):null,KW:f.teaser?g.Vj(f.teaser):null,Vn:f.icon?g.Vj(f.icon):null,imageUrl:T.image_url,displayDomain:T.display_domain?T.display_domain:null,showLinkIcon:!!T.show_link_icon,GQ:T.button_icon_url?T.button_icon_url:null,title:T.title,customMessage:T.custom_message?
T.custom_message:null,url:NL({pause_on_navigation:T.pause_on_navigation,target:T.target||"new",value:T.url}),LKL:k,MB4:T.signin_title?T.signin_title:void 0,i2C:T.signin_message?T.signin_message:void 0,offers:J,onClickCommand:null};hF(u,Y);break;case "simple":Y={id:Y.id,timestamp:T.timestamp||0,type:T.card_type,teaserText:T.teaser_text,teaserDurationMs:T.teaser_duration_ms,startMs:T.start_ms,autoOpen:T.auto_open||!1,sessionData:T.session_data||{},sponsored:T.sponsored||!1,HA:G,Vs:f.card?g.Vj(f.card):
null,KW:f.teaser?g.Vj(f.teaser):null,Vn:f.icon?g.Vj(f.icon):null,imageUrl:T.image_url,displayDomain:T.display_domain?T.display_domain:null,showLinkIcon:!!T.show_link_icon,GQ:T.button_icon_url?T.button_icon_url:null,title:T.title,customMessage:T.custom_message?T.custom_message:null,url:NL({pause_on_navigation:T.pause_on_navigation,target:T.target||"new",value:T.url}),onClickCommand:null};hF(u,Y);break;case "video":Y={id:Y.id,timestamp:T.timestamp||0,type:T.card_type,teaserText:T.teaser_text,teaserDurationMs:T.teaser_duration_ms,
startMs:T.start_ms,autoOpen:T.auto_open||!1,sessionData:T.session_data||{},sponsored:T.sponsored||!1,HA:G,Vs:f.card?g.Vj(f.card):null,KW:f.teaser?g.Vj(f.teaser):null,Vn:f.icon?g.Vj(f.icon):null,Yo:T.image_url,videoDuration:T.video_duration||null,customMessage:T.custom_message?T.custom_message:null,title:T.title,metaInfo:T.meta_info,isLiveNow:!!T.is_live_now,url:NL({pause_on_navigation:T.pause_on_navigation,target:T.target||"new",value:T.url}),onClickCommand:null},hF(u,Y)}}else bv$(z.K,T);Y=!0}}Y&&
(bh(z.player),z.ge())},XhF=function(z,t){var Y=!1;
z.K||(z.K=C_j(z),g.a(z,z.K));for(var K=g.r(t.cards||[]),T=K.next();!T.done;T=K.next())T=T.value,T.cardRenderer&&(V4V(z.K,T.cardRenderer),Y=!0);if(Y){var G;(G=z.player.getVideoData())!=null&&g.FK(G)||(Y=z.K,K=t.headerText?g.Hi(t.headerText):"",g.Tq(Y.LA,K),Y.B&&Y.B.setAttribute("title",K),Y.context.videoData.eventId&&(Y.eventId=Y.context.videoData.eventId),Y.qw=t.trackingParams?g.Vj(t.trackingParams):null,Y.C=t.closeButton.infoCardIconRenderer.trackingParams?g.Vj(t.closeButton.infoCardIconRenderer.trackingParams):
null,Y.Vn=t.icon.infoCardIconRenderer.trackingParams?g.Vj(t.icon.infoCardIconRenderer.trackingParams):null,z.ge());bh(z.player)}},DOV=function(z,t,Y,K,T){if(!z.player.G().YG){var G=[];
t.navigationEndpoint&&g.m(t.navigationEndpoint,g.Hy)&&g.m(t.navigationEndpoint,g.Hy).browseId&&G.push(new ivj("openUrl","click",new C36("/channel/"+g.m(t.navigationEndpoint,g.Hy).browseId,"new",!0,!0)));var v=t.watermark.thumbnails[0];K={channel_name:t.channelName,end_ms:t.endTimeMs,image_height:v.height,image_type:1,image_url:v.url,image_width:v.width,is_mobile:!1,session_data:{annotation_id:Y,ei:T,feature:"iv",itct:t.trackingParams,src_vid:K},start_ms:t.startTimeMs};if(t.subscribeButton&&g.m(t.subscribeButton,
g.Ur)){K.channel_id=g.m(t.subscribeButton,g.Ur).channelId;var f;t=g.m(t.subscribeButton,g.Ur);v=T=null;t.subscribed?(t.subscriberCountWithUnsubscribeText&&(T=g.Hi(t.subscriberCountWithUnsubscribeText)),t.subscriberCountText&&(v=g.Hi(t.subscriberCountText))):(t.subscriberCountText&&(T=g.Hi(t.subscriberCountText)),t.subscriberCountWithSubscribeText&&(v=g.Hi(t.subscriberCountWithSubscribeText)));var C,X=((C=g.m((f=t.signInEndpoint)==null?void 0:f.commandMetadata,g.rP))==null?void 0:C.url)||"";f={subscribeText:g.Hi(t.unsubscribedButtonText),
subscribeCount:T||"",unsubscribeText:g.Hi(t.subscribedButtonText),unsubscribeCount:v||"",enabled:t.enabled||!1,classic:!1,subscribed:t.subscribed||!1,feature:"iv",signInUrl:X};K.standalone_subscribe_button_data=f}G=new M4F(Y,"branding","branding",G,K);f=tiF(z);z.J.element.appendChild(f);G=new GO(f,Aw(z),G);G.jE();g.a(G,G);z.N[Y]=G}},vrF=function(z,t){return function(){var Y=g.ob.apply(0,arguments);
z.m6()||z.J3.push(g.md.Fw(function(){t.apply(null,g.b(Y))}))}},MiV=function(z){return z==="annotation-editor"||z==="live-dashboard"};
g.UQ.prototype.Dj=g.GE(45,function(z,t){var Y=g.cD(this.HV());Y&&Y.Dj(z,t)});
var n9={},FG=null;g.A2(cf,g.sn);g.q=cf.prototype;g.q.getDuration=function(){return this.duration};
g.q.play=function(z){if(z||this.K==0)this.progress=0,this.coords=this.J;else if(this.isPlaying())return!1;Qk(this);this.startTime=z=g.Gz();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.W=this.startTime;this.progress||this.JI();this.CN("play");this.isPaused()&&this.CN("resume");this.K=1;var t=g.t2(this);t in n9||(n9[t]=this);IyN();ayA(this,z);return!0};
g.q.stop=function(z){Qk(this);this.K=0;z&&(this.progress=1);gsF(this,this.progress);this.onStop();this.ZH()};
g.q.pause=function(){this.isPlaying()&&(Qk(this),this.K=-1,this.CN("pause"))};
g.q.W0=function(){this.K==0||this.stop(!1);this.CN("destroy");cf.LC.W0.call(this)};
g.q.destroy=function(){this.dispose()};
g.q.mP=function(){this.CN("animate")};
g.q.CN=function(z){this.dispatchEvent(new JYz(z,this))};
g.A2(JYz,g.E6);g.A2(uh,cf);uh.prototype.L=function(){};
uh.prototype.mP=function(){this.L();uh.LC.mP.call(this)};
uh.prototype.ZH=function(){this.L();uh.LC.ZH.call(this)};
uh.prototype.JI=function(){this.L();uh.LC.JI.call(this)};
g.A2(mc6,uh);mc6.prototype.L=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.p(eO6,g.I);g.q=eO6.prototype;g.q.listen=function(z,t,Y,K){Y=(0,g.YK)(Y,K||this.J);z=g.wt(z,t,Y);this.K.push(z);return z};
g.q.sP=function(z,t,Y,K){Y=(0,g.YK)(Y,K||this.J);z=L6N(z,t,Y);this.K.push(z);return z};
g.q.NL=function(z){g.b9(z);g.Zj(this.K,z)};
g.q.removeAll=function(){g.b9(this.K);this.K.length=0};
g.q.W0=function(){this.removeAll();g.I.prototype.W0.call(this)};g.p(SwW,g.Zc);g.q=SwW.prototype;g.q.load=function(){g.Zc.prototype.load.call(this);if(!ox(this)){var z=g.Zf0(this.player.getVideoData());z?(z=xcz(z,EsA(this)),L9(this,z,!1)):W6_(this)}};
g.q.unload=function(){L9(this,null);this.W&&(this.W.abort(),this.W=null);g.Zc.prototype.unload.call(this)};
g.q.KM=function(z,t){return ox(this)?z==="loadCustomEndscreenRenderer"?(z=xcz(t,"new"),L9(this,z),!0):null:null};
g.q.getOptions=function(){return ox(this)?["loadCustomEndscreenRenderer"]:[]};
g.q.T1=function(){if(this.endscreen&&this.endscreen.elements){var z=this.player.getVideoContentRect();if(z&&z.width!==0&&z.height!==0){var t=this.player.getPlayerSize();if(t&&t.width!==0&&t.height!==0){var Y=z.width/z.height;var K=0;for(var T=-1,G=0;G<l0W.length;G++){var v=Math.abs(t.width-l0W[G]);if(T===-1||K>=v)T=G,K=v}K=Z4$[T];this.L&&g.$R(this.L.element,"outline-width",Math.max(t.width,t.height)+"px");for(t=0;t<this.endscreen.elements.length;++t)if(G=this.endscreen.elements[t].id,T=this.J[G],
v=this.N[G],T&&v){var f=v.width*Y/v.aspectRatio,C=Math.round(v.width*z.width);G=Math.round(f*z.height);var X=z.left+Math.round(v.left*z.width),O=z.top+Math.round(v.top*z.height);g.yT(T.element,C,G);g.gZ(T.element,X,O);g.iz(T.element,qIN);C>256||G>256?g.f2(T.element,"ytp-ce-large-round"):C>96||G>96?g.f2(T.element,"ytp-ce-medium-round"):g.f2(T.element,"ytp-ce-small-round");g.iz(T.element,ph_);C=v.left+v.width/2;v=v.top+f/2;g.f2(T.element,C<=.5&&v<=.5?"ytp-ce-top-left-quad":C>.5&&v<=.5?"ytp-ce-top-right-quad":
C<=.5&&v>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.iz(T.element,Z4$);g.f2(T.element,K);(T=g.NH(document,"div","ytp-ce-expanding-overlay-body",T.element)[0])&&g.$R(T,"height",G+"px")}}}}};
g.q.onCueRangeEnter=function(z){if(this.endscreen)if(z.getId()==="ytp-ce-in-endscreen")g5(this,this.endscreen.impressionUrls),(z=g.Qj())&&this.endscreen.visualElement&&g.AA(z,this.endscreen.visualElement),this.K&&(g.f2(this.K,"ytp-ce-element-show"),this.K.removeAttribute("aria-hidden"),this.player.HW()?g.f2(this.K,"ytp-ce-hide-button-lower"):g.X0(this.K,"ytp-ce-hide-button-lower"));else{z=z.getId().substring(15);var t=this.J[z],Y=this.N[z];g.f2(t.element,"ytp-ce-element-show");t.element.removeAttribute("aria-hidden");
t=this.player.getRootNode();g.f2(t,"ytp-ce-shown");g5(this,Y.impressionUrls);(t=g.Qj())&&g.AA(t,Y.visualElement);this.player.G().B&&this.player.G5("endscreenelementshown",z)}};
g.q.onCueRangeExit=function(z){if(z.getId()==="ytp-ce-in-endscreen")this.K&&(g.X0(this.K,"ytp-ce-element-show"),this.K.setAttribute("aria-hidden","true"));else{z=z.getId().substring(15);var t=this.J[z];g.X0(t.element,"ytp-ce-element-show");t.element.setAttribute("aria-hidden","true");t=this.player.getRootNode();g.X0(t,"ytp-ce-shown");this.player.G().B&&this.player.G5("endscreenelementhidden",z)}};
g.q.of6=function(z){var t=this;z.target===window&&(new g.R0(function(){for(var Y=g.r(Object.values(t.J)),K=Y.next();!K.done;K=Y.next())g.iz(K.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.q.KU=function(z){for(var t=g.r(Object.values(this.J)),Y=t.next();!Y.done;Y=t.next())Y=Y.value,z?Y.element.setAttribute("hidden",""):Y.element.removeAttribute("hidden")};
g.q.sE0=function(z){this.K&&this.player.getRootNode().removeChild(this.K);z&&(g.f2(z,"ytp-ce-hide-button-container"),this.K=z,g.c$(this.player,this.K,4))};
var l0W=[346,426,470,506,570,640,853,1280,1920],Z4$="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),ph_=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],qIN=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var XM2={Put:"current",yCC:"new"};var Ov$={CLOSE:"close",Dn2:"openUrl",SUBSCRIBE:"subscribe"},s3_={puK:"click",CLOSE:"close",iW6:"hidden",OOo:"rollOut",bOt:"rollOver",Dig:"shown"};M4F.prototype.Of=function(){var z=lkK(this,function(t){return t.type==="openUrl"&&t.url!=null});
return z?z.url:null};
var sRw={AsL:"anchored",Dp:"branding",CHANNEL:"channel",Ktg:"cta",Ws6:"highlightText",AV5:"label",PLAYLIST:"playlist",POPUP:"popup",GRt:"speech",SUBSCRIBE:"subscribe",WDt:"title",VIDEO:"video",z0w:"website"},O4Q={Dp:"branding",mWK:"card",l7W:"drawer",LsC:"highlight",hPK:"marker",RXW:"promotion",TEXT:"text",kv2:"widget"};g.p(xN,g.I);g.q=xN.prototype;g.q.addCueRange=function(z,t,Y,K,T){z=new g.GT(z,t,{id:Y,namespace:"annotations_module"});K&&this.B0.set(z,K);T&&this.dW.set(z,T);this.context.S.Gc([z],1)};
g.q.jE=function(){this.context.J.subscribe("resize",this.Zu,this)};
g.q.EK=function(){return this.element};
g.q.O2=function(z,t,Y,K,T,G){if(this.KA)return!1;G&&(G.stopPropagation(),G.preventDefault());this.navigate(z,Y,K,T);return!1};
g.q.show=function(){};
g.q.hide=function(){};
g.q.destroy=function(){g.Ys(this.EK())};
g.q.Zu=function(){};
g.q.navigate=function(z,t,Y,K){var T=this,G=mm(z);if(G){var v=UAW(G,z.target),f=function(){z.K&&T.context.S.pauseVideo();var C=T.context.videoData.rb||!1,X=g.AV(G||"");C&&X&&(X.v||X.list)?T.context.S.WO(X.v,t,X.list,!1):g.xP(G||"",v==="current"?"_top":void 0,t)};
v==="new"&&(f(),f=null);vm(this.context.logger,Y,f,K);j36(G)||(Y=g.Qj(),K=t.itct,Y&&K&&g.XL(Y,g.Vj(K)))}};
g.q.W0=function(){this.B0.clear();this.dW.clear();g.I.prototype.W0.call(this)};
g.q.createElement=function(z){z=new g.e(z);g.a(this,z);return z.element};g.p(wMF,xN);g.q=wMF.prototype;g.q.jG=function(){this.J3&&hF(this,this.J3)};
g.q.isAvailable=function(){var z;if(z=!!this.cards.length)(z=this.S.getRootNode())?(z=g.e0(z),z=173<z.width&&173<z.height):z=!1;return z};
g.q.Zu=function(){var z=this.isAvailable();g.dZ(this.EK(),z);g.On(this.context.S.getRootNode(),g.Se.IV_DRAWER_ENABLED,z);bh(this.S)};
g.q.destroy=function(){this.S.Dj(!1);try{this.S.getRootNode().removeChild(this.W)}catch(z){}g.XA(this.P0);g.u9(this.U4);this.XC&&this.XC.dispose();this.U&&this.U.dispose();xN.prototype.destroy.call(this)};
g.q.M1=function(){var z=this;this.context.K.listen(g.yY("iv-drawer-close-button",this.W),"click",this.y$,this);this.context.K.listen(this.J,"touchend",function(){z.E4.start()});
this.context.K.listen(this.J,"scroll",this.L3,this);this.context.J.subscribe("onHideControls",function(){z.SL=!0});
this.context.J.subscribe("onShowControls",function(){z.SL=!1});
this.context.J.subscribe("onVideoAreaChange",function(){z.SL=g.Av(z.S.getRootNode(),"ytp-autohide")});
this.P0.push(g.CV("iv-button-shown",this.ML5,this));this.P0.push(g.CV("iv-button-hidden",this.io2,this));uZz(this)};
g.q.findLastIndex=function(z){if(this.cards.length===0)return 0;var t=g.sN(this.cards,function(Y){return z.AL.startMs>Y.AL.startMs||z.AL.startMs===Y.AL.startMs&&z.AL.timestamp>=Y.AL.timestamp?!0:!1});
return t===-1?0:t+1};
g.q.y$=function(){if(this.L){vm(this.context.logger,Ky(this).HA.close);var z=g.Qj();z&&this.C&&g.XL(z,this.C);Rx(this)}};
g.q.L3=function(){g.On(this.W,"iv-drawer-scrolled",this.J.scrollTop>0)};
g.q.ML5=function(){var z=g.Qj(),t=Ky(this);t=t?t.Vn:this.Vn;z&&t&&g.f1(z,[t])};
g.q.io2=function(){var z=g.Qj(),t=Ky(this);t=t?t.Vn:this.Vn;z&&t&&g.C1(z,[t])};
g.q.WS=function(){var z=Ky(this);vm(this.context.logger,z.HA.NV);var t=g.Qj();if(t&&z)if(this.S.X("web_infocards_teaser_show_logging_fix")){var Y=[];z.KW&&Y.push(z.KW);z.Vn&&Y.push(z.Vn);Y.length>0&&g.f1(t,Y)}else g.f1(t,[z.KW,z.Vn])};
g.q.L62=function(){var z=g.Qj(),t=Ky(this);z&&t&&g.C1(z,[t.KW])};
g.q.Ls=function(z){var t=Ky(this),Y=g.Qj();this.K?z?(z=this.context.logger,vm(z,t.HA.Vv),z.S.sendVideoStatsEngageEvent(4,void 0),Y&&t.KW&&g.XL(Y,t.KW)):(z=this.context.logger,vm(z,t.HA.Vv),z.S.sendVideoStatsEngageEvent(4,void 0),Y&&t.Vn&&g.XL(Y,t.Vn)):(z=this.context.logger,vm(z,t.HA.Vv),z.S.sendVideoStatsEngageEvent(4,void 0),Y&&this.Vn&&g.XL(Y,this.Vn))};g.p(TO,xN);TO.prototype.jE=function(){xN.prototype.jE.call(this);ak6(this)};
TO.prototype.show=function(){xN.prototype.show.call(this);var z=g.Qj(),t=this.annotation.data;z&&t&&(t=t.session_data)&&g.f1(z,[g.Vj(t.itct)])};
TO.prototype.hide=function(){xN.prototype.hide.call(this);var z=g.Qj(),t=this.annotation.data;z&&t&&(t=t.session_data)&&g.C1(z,[g.Vj(t.itct)])};g.p(GO,TO);
GO.prototype.show=function(){if(!this.isActive){TO.prototype.show.call(this);if(!this.C){g.f2(this.EK(),"iv-branding");var z=this.annotation.data;this.J=this.createElement({Z:"img",It:["branding-img","iv-click-target"],Y:{"aria-label":"Marca de agua del canal",src:z.image_url,width:z.image_width,height:z.image_height}});g.dZ(this.J,!1);var t=this.createElement({Z:"button",It:["branding-img-container","ytp-button"]});t.appendChild(this.J);this.EK().appendChild(t);var Y=this.annotation.Of();Y&&Sf(this,
t,Y,this.annotation.id,z.session_data);this.context.S.X("disable_branding_context")||NSN(this,z);this.C=!0}g.dZ(this.EK(),!0);this.isActive=!0;if(this.J){try{ghA(this,this.J)}catch(K){}g.f2(this.context.S.getRootNode(),"ytp-branding-shown");this.context.S.getRootNode().style.setProperty("--branding-image-width",this.J.getAttribute("width")+"px")}}};
GO.prototype.hide=function(){this.isActive&&(TO.prototype.hide.call(this),g.dZ(this.EK(),!1),this.isActive=!1,g.X0(this.context.S.getRootNode(),"ytp-branding-shown"))};
GO.prototype.destroy=function(){this.K&&(this.K.dispose(),this.K=null);g.X0(this.context.S.getRootNode(),"ytp-branding-shown");TO.prototype.destroy.call(this)};g.p(egj,TO);g.q=egj.prototype;g.q.show=function(){this.isActive||(TO.prototype.show.call(this),this.V||(xA2(this),this.V=!0),g.dZ(this.EK(),!0),g.Ia(function(){g.X0(this.EK(),"iv-promo-inactive")},100,this),this.EK().removeAttribute("aria-hidden"),this.isActive=!0,Rgw(this),SEN(this),EhN(this,this.N))};
g.q.hide=function(){this.isActive&&(g.f2(this.EK(),"iv-promo-inactive"),this.isActive=!1,this.EK().setAttribute("aria-hidden","true"))};
g.q.O2=function(z,t,Y,K,T,G){return this.isCollapsed?!1:TO.prototype.O2.call(this,z,t,Y,K,T,G)};
g.q.A8=function(z){this.B=!0;dAW(this,500,z)};
g.q.dZ=function(){this.B=!1;W12(this)};
g.q.D8=function(z){z.stopPropagation();this.hide()};
g.q.Fe=function(z){z.stopPropagation();Rgw(this);this.isCollapsed=!0;g.f2(this.EK(),"iv-promo-collapsed-no-delay");this.U.start()};
g.q.destroy=function(){this.U.dispose();TO.prototype.destroy.call(this)};g.p(zGA,g.Zc);g.q=zGA.prototype;g.q.KM=function(z,t){if(!MiV(this.player.G().playerStyle))return null;switch(z){case "loadCustomAnnotationsXml":return(z=g.Ep(t))&&GoN(this,z),!0;case "removeCustomAnnotationById":return t&&this.K&&(F1N(this.K,t),bh(this.player)),!0}return null};
g.q.getOptions=function(){return MiV(this.player.G().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.q.Jz=function(){var z=this.player.G(),t=this.player.getVideoData(),Y=z.annotationsLoadPolicy||t.annotationsLoadPolicy;return g.xx(t)||this.player.isMutedByEmbedsMutedAutoplay()?!1:Y===1&&!t.Ul||z.SL.get(t.videoId)||g.Q6(t)||g.cy(t)?!0:!1};
g.q.ge=function(){if(this.L){var z=this.player.VK().getVideoContentRect(!0);g.yT(this.L.element,z.width,z.height);g.gZ(this.L.element,z.left,z.top)}if(this.K){var t=this.player.yI();z=this.K;t=t.width;g.On(z.W,"iv-drawer-small",t<=426);g.On(z.W,"iv-drawer-big",t>=1280)}};
g.q.Ra=function(z){YIj(this,z.state);g.x(z.state,2)&&(this.HW()&&this.Gv()&&this.player.getPresentingPlayerType()!==2&&this.FZ(!1),this.Dj(!1))};
g.q.load=function(){function z(v){var f=t.loadNumber;t.U=null;t.loaded&&t.loadNumber===f&&t.player.getVideoData().videoId===K&&(v=g.Z7(v)&&v.responseXML?v.responseXML:null)&&(GoN(t,v),g.f2(t.player.getRootNode(),"iv-module-loaded"))}
var t=this;g.Zc.prototype.load.call(this);YIj(this,this.player.getPlayerStateObject());this.loadNumber++;var Y=this.player.getVideoData(),K=Y.videoId;g.TZ()&&(z=vrF(this,z));var T={format:"XML",onFinish:z,onError:function(){t.U=null},
urlParams:{}};Y.isPharma&&(T.urlParams.pharma="1");T.method="POST";T.withCredentials=!0;var G=this.player.G().SL.get(K);G&&AK6(T,G);G=G&&(G.B9||G.N1);if(!Y.EY||G)Y.U4?KK_(this,Y.U4,T):(this.C=function(){if(!t.B)t.onVideoDataChange(T);var v=t.player.getVideoData();(v==null?0:g.FK(v))&&!t.P0&&i4w(t,v)},this.player.addEventListener("videodatachange",this.C));
g.c$(this.player,this.L.element,4);this.ge();(G=g.Q6(Y))&&XhF(this,G);(G=g.cy(Y))&&G.featuredChannel&&DOV(this,G.featuredChannel,G.annotationId||"branding",Y.videoId||null,Y.eventId||null);this.l1=g.yY("ytp-cards-button",this.player.getRootNode());g.FK(Y)&&i4w(this,Y)};
g.q.onVideoDataChange=function(z){var t=this.player.getVideoData();t.U4&&KK_(this,t.U4,z)};
g.q.unload=function(){this.player.xf("annotations_module");for(var z=g.r(Object.keys(this.N)),t=z.next();!t.done;t=z.next())this.N[t.value].destroy();this.V=null;this.K&&(this.K.destroy(),this.K=null,bh(this.player));this.B=!1;this.U&&(this.U.abort(),this.U=null);this.P0=!1;this.N={};this.J.hide();g.Zc.prototype.unload.call(this);this.L.detach();this.C&&(this.player.removeEventListener("videodatachange",this.C),this.C=null)};
g.q.x7=function(z){z===this.player.getVideoData().videoId&&(this.loaded?f0N(this):this.load())};
g.q.HW=function(){var z;return((z=this.K)==null?void 0:z.isAvailable())||this.P0};
g.q.Gv=function(){return!!this.K&&this.K.L};
g.q.FZ=function(z,t,Y){t=t===void 0?!1:t;this.HW();this.K&&(z?Y?Wf(this.K,Y,t):Wf(this.K,"YOUTUBE_DRAWER_AUTO_OPEN",t):Rx(this.K))};
g.q.Dj=function(z,t){this.player.publish(z?"cardsteasershow":"cardsteaserhide",t)};
g.q.W0=function(){this.player.G().SL.unsubscribe("vast_info_card_add",this.x7,this);g.X0(this.player.getRootNode(),g.Se.IV_DRAWER_OPEN);for(var z=this.J3,t=g.md,Y=0,K=z.length;Y<K;Y++)t.EM(z[Y]);this.J3.length=0;g.Zc.prototype.W0.call(this)};
g.q.createElement=function(z){z=new g.e(z);g.a(this,z);return z.element};g.lD("annotations_module",zGA);g.lD("creatorendscreen",SwW);})(_yt_player);
